const actions = {
  APP: {
    INITIAL_LOAD: 'INITIAL_LOAD',
    INITIAL_LOAD_ERROR: 'INITIAL_LOAD_ERROR',
    USER_LOAD: 'USER_LOAD',
    LOAD_RATE: 'LOAD_RATE',
    APP_ERROR: 'APP_ERROR'
  },
	SIGNUP: {
    MOBILE_INPUT: 'MOBILE_INPUT',
    SIGNIN_ACCOUNT: 'SIGNIN_ACCOUNT',
    SIGNIN_ACCOUNT_ERR: 'SIGNIN_ACCOUNT_ERR',       
    SIGNUP_ACCOUNT: 'SIGNUP_ACCOUNT',
    SIGNUP_ACCOUNT_ERR: 'SIGNUP_ACCOUNT_ERR',
    TOGGLE_OTP: 'TOGGLE_OTP',
    LOADING_OTP: 'LOADING_OTP'
  },
  DASHBOARD: {
    INITIAL_LOAD: 'INITIAL_LOAD'
  }
};

export default actions;
